### ISSUE TITLE
Scanning QR code seems like doesn't working.

### ISSUE THREAD

**Issue by anilkilic** [BoomApps-LLC/SteemApp-iOS#1]
QR Scanner for PPK is having trouble on small size, when I open QR code image in a new tab, grabs it immediately but puts an *http://* string to password area and that's all.

Device: IPhone 5S
OS: iOS 11.4

^ this happened on the released app store version. Not the beta. I just applied for beta access.

**Comment by yuriks2000** [comment]
You need to click on the small QR code in browser. Small qr is an empty link

**Comment by anilkilic** [comment]
Didn't knew about that, thank you.

**Comment by yuriks2000** [comment]
Yeah, I did not know about that too, same as many other people. Only when started to develop a qr login we found out. That is why we did the onboarding about QR and private keys, to make it easier for people to sign in. Did you see the onboarding by the way?

**Comment by anilkilic** [comment]
Yes, I've seen it but I guess most of us just fast forwards onboarding screens.
