### ISSUE TITLE
2.0(7) - Unable to vote and infinite vote loading indicator

### ISSUE THREAD

**Issue by tobias-g1** [BoomApps-LLC/SteemApp-iOS#4]
#### Expected behavior

You should be able to vote for posts within the application. 

#### Actual behaviour

You're unable to vote for posts using the application and instead, it shows an infinite loading indicator and your vote is not cast. 

#### How to reproduce

1. Go to feed and press the top post. 
2. Click upvote. 
3. Note that the upvote doesn't take place and will show the loading sign for a long period of time until to press back on the page. 
4. Go to Steemd for the account you made the vote and check if the vote was cast. Note that the vote wasn't cast. 

#### Recording of issue

The following video shows this issue in more detail:

https://www.youtube.com/embed/P3hLtQxwLso

#### Environment

- Device:  iPhone 5S 16gb
- Operating system: iOS 11.4
- Application Version of Testing: 2.0 (7)

**Comment by josephace135** [comment]
@tobias-g1 I have noticed that one too yesterday but wasn't able to post. But upon trying out today,
the upvote works and is logged in the steemblockexplorer.

Environment

* Device: iPhone 5S 16gb
* Operating system: iOS 11.4
* Application Version of Testing: 2.0 (7)

**Comment by tobias-g1** [comment]
I was also able to get it to vote eventually, killing the application and voting again. I did, however, get the long loading indicator, but when checking the vote within my profile it was cast.  I believe this issue is either is related to the first use of the application or is intermittent.

**Comment by mby4github** [comment]
Hi josephace135, seems this is a bug. It seems the error is returned but is not processed proper way (that's why animation doesn't disappear). Will fix. Thanks for you bug report.

**Comment by mby4github** [comment]
Fixed in 08389c80f3614758a0545302bd23109d137a8733
