### ISSUE TITLE
Alphanumeric Characters are shown when manually entering or when using QR Code Scanning for the Posting Key

### ISSUE THREAD

**Issue by josephace135** [BoomApps-LLC/SteemApp-iOS#5]
#### Expected behavior
Before logging in to SteemApp application, the alphanumeric characters of the Posting Key should be represented by bullets, be it manually typed or using the QR Code scanning method.

#### Actual behavior
Upon manually entering the alphanumeric characters of the Posting Key, the alphanumeric characters are visible. Additionally, when using the QR Code scanning method, the alphanumeric characters are visible too.

#### How to reproduce
* Open SteemApp 2.0 (7) application.
* Enter **Steemit username**.
* Manually enter your **Private Posting Key** or use the **QR Code Scanning** method in entering the **Private Posting Key**.
* Instead of being replaced or represented with bullets, the alphanumeric characters are visible.

* Browser/App version: SteemApp 2.0 (7)
* Device: iPhone 6 64GB
* Operating system: iOS 11.4

#### Recording Of The Bug
https://www.youtube.com/watch?v=joZa37HhOgA

**Comment by mby4github** [comment]
Hi josephace135, we decided to show letters instead of bullets because the **Private posting key** is not readable like password. Nobody can spy it and remember. That's why maybe better to leave it visible.

**Comment by josephace135** [comment]
Okay @mby4github
